// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package auto

const TableNameArea = "area"

// Area mapped from table <area>
type Area struct {
	ID    string `gorm:"column:id;primaryKey;comment:区域id,和文件对应" json:"id"`                               // 区域id,和文件对应
	Level string `gorm:"column:level;comment:区域级别，从高到低country,province,city,district,更细的待定" json:"level"` // 区域级别，从高到低country,province,city,district,更细的待定
	Name  string `gorm:"column:name;comment:区域名称" json:"name"`                                            // 区域名称
	Pid   string `gorm:"column:pid;not null;comment:父级区域id" json:"pid"`                                   // 父级区域id
}

// TableName Area's table name
func (*Area) TableName() string {
	return TableNameArea
}
