// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package auto

const TableNameCoreStore = "core_store"

// CoreStore mapped from table <core_store>
type CoreStore struct {
	ID           int64 `gorm:"column:id;primaryKey;comment:ID" json:"id"`                       // ID
	ResourceID   int64 `gorm:"column:resource_id;not null;comment:资源ID" json:"resource_id"`     // 资源ID
	UID          int64 `gorm:"column:uid;not null;comment:用户ID" json:"uid"`                     // 用户ID
	ResourceType int32 `gorm:"column:resource_type;not null;comment:资源类型" json:"resource_type"` // 资源类型
	Time         int64 `gorm:"column:time;not null;comment:收藏时间" json:"time"`                   // 收藏时间
}

// TableName CoreStore's table name
func (*CoreStore) TableName() string {
	return TableNameCoreStore
}
