// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package auto

const TableNameCoreCopilotConfig = "core_copilot_config"

// CoreCopilotConfig copilot配置信息表
type CoreCopilotConfig struct {
	ID         int64  `gorm:"column:id;primaryKey;comment:ID" json:"id"`                  // ID
	CopilotURL string `gorm:"column:copilot_url;comment:copilot服务端地址" json:"copilot_url"` // copilot服务端地址
	Username   string `gorm:"column:username;comment:用户名" json:"username"`                // 用户名
	Pwd        string `gorm:"column:pwd;comment:密码" json:"pwd"`                           // 密码
}

// TableName CoreCopilotConfig's table name
func (*CoreCopilotConfig) TableName() string {
	return TableNameCoreCopilotConfig
}
