// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package auto

const TableNameCoreOptRecent = "core_opt_recent"

// CoreOptRecent mapped from table <core_opt_recent>
type CoreOptRecent struct {
	ID           int64  `gorm:"column:id;primaryKey;comment:ID" json:"id"`                       // ID
	ResourceID   int64  `gorm:"column:resource_id;comment:资源ID" json:"resource_id"`              // 资源ID
	ResourceName string `gorm:"column:resource_name;comment:资源名称" json:"resource_name"`          // 资源名称
	UID          int64  `gorm:"column:uid;not null;comment:用户ID" json:"uid"`                     // 用户ID
	ResourceType int32  `gorm:"column:resource_type;not null;comment:资源类型" json:"resource_type"` // 资源类型
	OptType      int32  `gorm:"column:opt_type;comment:1 新建 2 修改" json:"opt_type"`               // 1 新建 2 修改
	Time         int64  `gorm:"column:time;not null;comment:收藏时间" json:"time"`                   // 收藏时间
}

// TableName CoreOptRecent's table name
func (*CoreOptRecent) TableName() string {
	return TableNameCoreOptRecent
}
