// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package auto

const TableNameCoreDatasourceTaskLog = "core_datasource_task_log"

// CoreDatasourceTaskLog mapped from table <core_datasource_task_log>
type CoreDatasourceTaskLog struct {
	ID                int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键" json:"id"` // 主键
	DsID              int64  `gorm:"column:ds_id;not null;comment:数据源ID" json:"ds_id"`             // 数据源ID
	TaskID            int64  `gorm:"column:task_id;comment:任务ID" json:"task_id"`                   // 任务ID
	StartTime         int64  `gorm:"column:start_time;comment:开始时间" json:"start_time"`             // 开始时间
	EndTime           int64  `gorm:"column:end_time;comment:结束时间" json:"end_time"`                 // 结束时间
	TaskStatus        string `gorm:"column:task_status;not null;comment:执行状态" json:"task_status"`  // 执行状态
	PhysicalTableName string `gorm:"column:table_name;not null;comment:表名" json:"table_name"`      // 表名
	Info              string `gorm:"column:info;comment:错误信息" json:"info"`                         // 错误信息
	CreateTime        int64  `gorm:"column:create_time;comment:创建时间" json:"create_time"`           // 创建时间
	TriggerType       string `gorm:"column:trigger_type" json:"trigger_type"`
}

// TableName CoreDatasourceTaskLog's table name
func (*CoreDatasourceTaskLog) TableName() string {
	return TableNameCoreDatasourceTaskLog
}
