// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package auto

const TableNameCoreExportDownloadTask = "core_export_download_task"

// CoreExportDownloadTask 下载任务列表
type CoreExportDownloadTask struct {
	ID         string `gorm:"column:id;primaryKey" json:"id"`
	CreateTime int64  `gorm:"column:create_time" json:"create_time"`
	ValidTime  int64  `gorm:"column:valid_time" json:"valid_time"`
}

// TableName CoreExportDownloadTask's table name
func (*CoreExportDownloadTask) TableName() string {
	return TableNameCoreExportDownloadTask
}
