// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package auto

const TableNameCoreSysStartupJob = "core_sys_startup_job"

// CoreSysStartupJob 项目启动任务
type CoreSysStartupJob struct {
	ID     string `gorm:"column:id;primaryKey;comment:ID" json:"id"` // ID
	Name   string `gorm:"column:name;comment:任务名称" json:"name"`      // 任务名称
	Status string `gorm:"column:status;comment:任务状态" json:"status"`  // 任务状态
}

// TableName CoreSysStartupJob's table name
func (*CoreSysStartupJob) TableName() string {
	return TableNameCoreSysStartupJob
}
