// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package auto

const TableNameCoreDatasourceTask = "core_datasource_task"

// CoreDatasourceTask mapped from table <core_datasource_task>
type CoreDatasourceTask struct {
	ID              int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键" json:"id"`         // 主键
	DsID            int64  `gorm:"column:ds_id;not null;comment:数据源ID" json:"ds_id"`                     // 数据源ID
	Name            string `gorm:"column:name;not null;comment:任务名称" json:"name"`                        // 任务名称
	UpdateType      string `gorm:"column:update_type;not null;comment:更新方式" json:"update_type"`          // 更新方式
	StartTime       int64  `gorm:"column:start_time;comment:开始时间" json:"start_time"`                     // 开始时间
	SyncRate        string `gorm:"column:sync_rate;not null;comment:执行频率：0 一次性 1 cron" json:"sync_rate"` // 执行频率：0 一次性 1 cron
	Cron            string `gorm:"column:cron;comment:cron表达式" json:"cron"`                              // cron表达式
	SimpleCronValue int64  `gorm:"column:simple_cron_value;comment:简单重复间隔" json:"simple_cron_value"`     // 简单重复间隔
	SimpleCronType  string `gorm:"column:simple_cron_type;comment:简单重复类型：分、时、天" json:"simple_cron_type"` // 简单重复类型：分、时、天
	EndLimit        string `gorm:"column:end_limit;comment:结束限制 0 无限制 1 设定结束时间" json:"end_limit"`        // 结束限制 0 无限制 1 设定结束时间
	EndTime         int64  `gorm:"column:end_time;comment:结束时间" json:"end_time"`                         // 结束时间
	CreateTime      int64  `gorm:"column:create_time;comment:创建时间" json:"create_time"`                   // 创建时间
	LastExecTime    int64  `gorm:"column:last_exec_time;comment:上次执行时间" json:"last_exec_time"`           // 上次执行时间
	LastExecStatus  string `gorm:"column:last_exec_status;comment:上次执行结果" json:"last_exec_status"`       // 上次执行结果
	ExtraData       string `gorm:"column:extra_data" json:"extra_data"`
	TaskStatus      string `gorm:"column:task_status;comment:任务状态" json:"task_status"` // 任务状态
}

// TableName CoreDatasourceTask's table name
func (*CoreDatasourceTask) TableName() string {
	return TableNameCoreDatasourceTask
}
