// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package auto

const TableNameCoreDriver = "core_driver"

// CoreDriver 驱动
type CoreDriver struct {
	ID          int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键" json:"id"` // 主键
	Name        string `gorm:"column:name;not null;comment:名称" json:"name"`                  // 名称
	CreateTime  int64  `gorm:"column:create_time;not null;comment:创建时间" json:"create_time"`  // 创建时间
	Type        string `gorm:"column:type;comment:数据源类型" json:"type"`                        // 数据源类型
	DriverClass string `gorm:"column:driver_class;comment:驱动类" json:"driver_class"`          // 驱动类
	Description string `gorm:"column:description;comment:描述" json:"description"`             // 描述
}

// TableName CoreDriver's table name
func (*CoreDriver) TableName() string {
	return TableNameCoreDriver
}
