// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package auto

const TableNameCoreFont = "core_font"

// CoreFont 字体表
type CoreFont struct {
	ID            int64   `gorm:"column:id;primaryKey;comment:ID" json:"id"`                    // ID
	Name          string  `gorm:"column:name;not null;comment:字体名称" json:"name"`                // 字体名称
	FileName      string  `gorm:"column:file_name;comment:文件名称" json:"file_name"`               // 文件名称
	FileTransName string  `gorm:"column:file_trans_name;comment:文件转换名称" json:"file_trans_name"` // 文件转换名称
	IsDefault     bool    `gorm:"column:is_default;comment:是否默认" json:"is_default"`             // 是否默认
	UpdateTime    int64   `gorm:"column:update_time;not null;comment:更新时间" json:"update_time"`  // 更新时间
	IsBuiltIn     bool    `gorm:"column:is_BuiltIn;comment:是否内置" json:"is_BuiltIn"`             // 是否内置
	Size          float64 `gorm:"column:size;comment:文件大小" json:"size"`                         // 文件大小
	SizeType      string  `gorm:"column:size_type;comment:存储单位" json:"size_type"`               // 存储单位
}

// TableName CoreFont's table name
func (*CoreFont) TableName() string {
	return TableNameCoreFont
}
