// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package auto

const TableNameCoreAreaCustom = "core_area_custom"

// CoreAreaCustom mapped from table <core_area_custom>
type CoreAreaCustom struct {
	ID   string `gorm:"column:id;primaryKey;comment:主键" json:"id"`        // 主键
	Name string `gorm:"column:name;not null;comment:自定义区域名称" json:"name"` // 自定义区域名称
	Pid  string `gorm:"column:pid;not null;comment:父级ID" json:"pid"`      // 父级ID
}

// TableName CoreAreaCustom's table name
func (*CoreAreaCustom) TableName() string {
	return TableNameCoreAreaCustom
}
