// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package auto

const TableNameCoreDriverJar = "core_driver_jar"

// CoreDriverJar 驱动详情
type CoreDriverJar struct {
	ID          int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键" json:"id"`  // 主键
	DeDriverID  string `gorm:"column:de_driver_id;not null;comment:驱动主键" json:"de_driver_id"` // 驱动主键
	FileName    string `gorm:"column:file_name;comment:名称" json:"file_name"`                  // 名称
	Version     string `gorm:"column:version;comment:版本" json:"version"`                      // 版本
	DriverClass string `gorm:"column:driver_class;comment:驱动类" json:"driver_class"`           // 驱动类
	TransName   string `gorm:"column:trans_name" json:"trans_name"`
	IsTransName bool   `gorm:"column:is_trans_name" json:"is_trans_name"`
}

// TableName CoreDriverJar's table name
func (*CoreDriverJar) TableName() string {
	return TableNameCoreDriverJar
}
