// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package auto

const TableNameCoreCopilotToken = "core_copilot_token"

// CoreCopilotToken copilot token记录表
type CoreCopilotToken struct {
	ID         int64  `gorm:"column:id;primaryKey;comment:ID" json:"id"`          // ID
	Type       string `gorm:"column:type;comment:free or license" json:"type"`    // free or license
	Token      string `gorm:"column:token;comment:token值" json:"token"`           // token值
	UpdateTime int64  `gorm:"column:update_time;comment:更新时间" json:"update_time"` // 更新时间
}

// TableName CoreCopilotToken's table name
func (*CoreCopilotToken) TableName() string {
	return TableNameCoreCopilotToken
}
