// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package auto

const TableNameCoreCustomGeoArea = "core_custom_geo_area"

// CoreCustomGeoArea 自定义地理区域
type CoreCustomGeoArea struct {
	ID   string `gorm:"column:id;primaryKey;comment:id" json:"id"` // id
	Name string `gorm:"column:name;comment:区域名称" json:"name"`      // 区域名称
}

// TableName CoreCustomGeoArea's table name
func (*CoreCustomGeoArea) TableName() string {
	return TableNameCoreCustomGeoArea
}
