// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package auto

const TableNameCoreMenu = "core_menu"

// CoreMenu mapped from table <core_menu>
type CoreMenu struct {
	ID        int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键" json:"id"`      // 主键
	Pid       int64  `gorm:"column:pid;not null;comment:父ID" json:"pid"`                        // 父ID
	Type      int32  `gorm:"column:type;comment:类型" json:"type"`                                // 类型
	Name      string `gorm:"column:name;comment:名称" json:"name"`                                // 名称
	Component string `gorm:"column:component;comment:组件" json:"component"`                      // 组件
	MenuSort  int32  `gorm:"column:menu_sort;comment:排序" json:"menu_sort"`                      // 排序
	Icon      string `gorm:"column:icon;comment:图标" json:"icon"`                                // 图标
	Path      string `gorm:"column:path;comment:路径" json:"path"`                                // 路径
	Hidden    bool   `gorm:"column:hidden;not null;comment:隐藏" json:"hidden"`                   // 隐藏
	InLayout  bool   `gorm:"column:in_layout;not null;default:1;comment:是否内部" json:"in_layout"` // 是否内部
	Auth      bool   `gorm:"column:auth;not null;comment:参与授权" json:"auth"`                     // 参与授权
}

// TableName CoreMenu's table name
func (*CoreMenu) TableName() string {
	return TableNameCoreMenu
}
