// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package auto

const TableNameCoreExportTask = "core_export_task"

// CoreExportTask 导出任务表
type CoreExportTask struct {
	ID                string  `gorm:"column:id;primaryKey;comment:主键" json:"id"`                            // 主键
	UserID            int64   `gorm:"column:user_id;not null;comment:用户ID" json:"user_id"`                  // 用户ID
	FileName          string  `gorm:"column:file_name;comment:文件名称" json:"file_name"`                       // 文件名称
	FileSize          float64 `gorm:"column:file_size;comment:文件大小" json:"file_size"`                       // 文件大小
	FileSizeUnit      string  `gorm:"column:file_size_unit;comment:单位" json:"file_size_unit"`               // 单位
	ExportFrom        string  `gorm:"column:export_from;comment:导出来源ID" json:"export_from"`                 // 导出来源ID
	ExportStatus      string  `gorm:"column:export_status;comment:导出状态" json:"export_status"`               // 导出状态
	ExportFromType    string  `gorm:"column:export_from_type;comment:导出来源类型" json:"export_from_type"`       // 导出来源类型
	ExportTime        int64   `gorm:"column:export_time;comment:导出时间" json:"export_time"`                   // 导出时间
	ExportProgress    string  `gorm:"column:export_progress;comment:导出进度" json:"export_progress"`           // 导出进度
	ExportMachineName string  `gorm:"column:export_machine_name;comment:导出机器名称" json:"export_machine_name"` // 导出机器名称
	Params            string  `gorm:"column:params;not null;comment:过滤参数" json:"params"`                    // 过滤参数
	Msg               string  `gorm:"column:msg;comment:错误信息" json:"msg"`                                   // 错误信息
}

// TableName CoreExportTask's table name
func (*CoreExportTask) TableName() string {
	return TableNameCoreExportTask
}
