// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package auto

const TableNameCoreDsFinishPage = "core_ds_finish_page"

// CoreDsFinishPage 是否显示完成页面记录表
type CoreDsFinishPage struct {
	ID int64 `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键" json:"id"` // 主键
}

// TableName CoreDsFinishPage's table name
func (*CoreDsFinishPage) TableName() string {
	return TableNameCoreDsFinishPage
}
