// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package auto

const TableNameCoreDeEngine = "core_de_engine"

// CoreDeEngine mapped from table <core_de_engine>
type CoreDeEngine struct {
	ID             int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键" json:"id"`               // 主键
	Name           string `gorm:"column:name;comment:名称" json:"name"`                                         // 名称
	Description    string `gorm:"column:description;comment:描述" json:"description"`                           // 描述
	Type           string `gorm:"column:type;not null;comment:类型" json:"type"`                                // 类型
	Configuration  string `gorm:"column:configuration;not null;comment:详细信息" json:"configuration"`            // 详细信息
	CreateTime     int64  `gorm:"column:create_time;comment:Create timestamp" json:"create_time"`             // Create timestamp
	UpdateTime     int64  `gorm:"column:update_time;comment:Update timestamp" json:"update_time"`             // Update timestamp
	CreateBy       string `gorm:"column:create_by;comment:创建人ID" json:"create_by"`                            // 创建人ID
	Status         string `gorm:"column:status;comment:状态" json:"status"`                                     // 状态
	EnableDataFill int32  `gorm:"column:enable_data_fill;default:1;comment:启用数据填报功能" json:"enable_data_fill"` // 启用数据填报功能
}

// TableName CoreDeEngine's table name
func (*CoreDeEngine) TableName() string {
	return TableNameCoreDeEngine
}
