// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package auto

const TableNameCoreAPITraffic = "core_api_traffic"

// CoreAPITraffic API并发限流阈值设置表
type CoreAPITraffic struct {
	ID        int64  `gorm:"column:id;primaryKey;comment:ID" json:"id"`                       // ID
	API       string `gorm:"column:api;not null;comment:api" json:"api"`                      // api
	Threshold int32  `gorm:"column:threshold;not null;default:2;comment:阈值" json:"threshold"` // 阈值
	Alive     int32  `gorm:"column:alive;not null;comment:活动并发" json:"alive"`                 // 活动并发
}

// TableName CoreAPITraffic's table name
func (*CoreAPITraffic) TableName() string {
	return TableNameCoreAPITraffic
}
