// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package auto

const TableNameCoreRsa = "core_rsa"

// CoreRsa mapped from table <core_rsa>
type CoreRsa struct {
	ID         int32  `gorm:"column:id;primaryKey;comment:主键" json:"id"`                   // 主键
	PrivateKey string `gorm:"column:private_key;not null;comment:私钥" json:"private_key"`   // 私钥
	PublicKey  string `gorm:"column:public_key;not null;comment:公钥" json:"public_key"`     // 公钥
	CreateTime int64  `gorm:"column:create_time;not null;comment:生成时间" json:"create_time"` // 生成时间
	AesKey     string `gorm:"column:aes_key;not null" json:"aes_key"`
}

// TableName CoreRsa's table name
func (*CoreRsa) TableName() string {
	return TableNameCoreRsa
}
