// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package auto

const TableNameCoreShareTicket = "core_share_ticket"

// CoreShareTicket 分享Ticket表
type CoreShareTicket struct {
	ID         int64  `gorm:"column:id;primaryKey;comment:ID" json:"id"`            // ID
	UUID       string `gorm:"column:uuid;not null;comment:分享uuid" json:"uuid"`      // 分享uuid
	Ticket     string `gorm:"column:ticket;not null;comment:ticket" json:"ticket"`  // ticket
	Exp        int64  `gorm:"column:exp;comment:ticket有效期" json:"exp"`              // ticket有效期
	Args       string `gorm:"column:args;comment:ticket参数" json:"args"`             // ticket参数
	AccessTime int64  `gorm:"column:access_time;comment:首次访问时间" json:"access_time"` // 首次访问时间
}

// TableName CoreShareTicket's table name
func (*CoreShareTicket) TableName() string {
	return TableNameCoreShareTicket
}
