// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package auto

const TableNameCoreDatasource = "core_datasource"

// CoreDatasource mapped from table <core_datasource>
type CoreDatasource struct {
	ID             int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键" json:"id"`     // 主键
	Name           string `gorm:"column:name;not null;comment:名称" json:"name"`                      // 名称
	Description    string `gorm:"column:description;comment:描述" json:"description"`                 // 描述
	Type           string `gorm:"column:type;not null;comment:类型" json:"type"`                      // 类型
	Pid            int64  `gorm:"column:pid;comment:父级ID" json:"pid"`                               // 父级ID
	EditType       string `gorm:"column:edit_type;comment:更新方式：0：替换；1：追加" json:"edit_type"`         // 更新方式：0：替换；1：追加
	Configuration  string `gorm:"column:configuration;not null;comment:详细信息" json:"configuration"`  // 详细信息
	CreateTime     int64  `gorm:"column:create_time;not null;comment:创建时间" json:"create_time"`      // 创建时间
	UpdateTime     int64  `gorm:"column:update_time;not null;comment:更新时间" json:"update_time"`      // 更新时间
	UpdateBy       int64  `gorm:"column:update_by;comment:变更人" json:"update_by"`                    // 变更人
	CreateBy       string `gorm:"column:create_by;comment:创建人ID" json:"create_by"`                  // 创建人ID
	Status         string `gorm:"column:status;comment:状态" json:"status"`                           // 状态
	QrtzInstance   string `gorm:"column:qrtz_instance;comment:状态" json:"qrtz_instance"`             // 状态
	TaskStatus     string `gorm:"column:task_status;comment:任务状态" json:"task_status"`               // 任务状态
	EnableDataFill int32  `gorm:"column:enable_data_fill;comment:启用数据填报功能" json:"enable_data_fill"` // 启用数据填报功能
}

// TableName CoreDatasource's table name
func (*CoreDatasource) TableName() string {
	return TableNameCoreDatasource
}
