// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package auto

const TableNameCoreChartView = "core_chart_view"

// CoreChartView mapped from table <core_chart_view>
type CoreChartView struct {
	ID                int64   `gorm:"column:id;primaryKey;comment:ID" json:"id"`                                                              // ID
	Title             string  `gorm:"column:title;comment:标题" json:"title"`                                                                   // 标题
	SceneID           int64   `gorm:"column:scene_id;not null;comment:场景ID chart_type为private的时候 是仪表板id" json:"scene_id"`                     // 场景ID chart_type为private的时候 是仪表板id
	TableID           int64   `gorm:"column:table_id;comment:数据集表ID" json:"table_id"`                                                         // 数据集表ID
	Type              string  `gorm:"column:type;comment:图表类型" json:"type"`                                                                   // 图表类型
	Render            string  `gorm:"column:render;comment:图表渲染方式" json:"render"`                                                             // 图表渲染方式
	ResultCount       int32   `gorm:"column:result_count;comment:展示结果" json:"result_count"`                                                   // 展示结果
	ResultMode        string  `gorm:"column:result_mode;comment:展示模式" json:"result_mode"`                                                     // 展示模式
	XAxis             string  `gorm:"column:x_axis;comment:横轴field" json:"x_axis"`                                                            // 横轴field
	XAxisExt          string  `gorm:"column:x_axis_ext;comment:table-row" json:"x_axis_ext"`                                                  // table-row
	YAxis             string  `gorm:"column:y_axis;comment:纵轴field" json:"y_axis"`                                                            // 纵轴field
	YAxisExt          string  `gorm:"column:y_axis_ext;comment:副轴" json:"y_axis_ext"`                                                         // 副轴
	ExtStack          string  `gorm:"column:ext_stack;comment:堆叠项" json:"ext_stack"`                                                          // 堆叠项
	ExtBubble         string  `gorm:"column:ext_bubble;comment:气泡大小" json:"ext_bubble"`                                                       // 气泡大小
	ExtLabel          string  `gorm:"column:ext_label;comment:动态标签" json:"ext_label"`                                                         // 动态标签
	ExtTooltip        string  `gorm:"column:ext_tooltip;comment:动态提示" json:"ext_tooltip"`                                                     // 动态提示
	CustomAttr        string  `gorm:"column:custom_attr;comment:图形属性" json:"custom_attr"`                                                     // 图形属性
	CustomAttrMobile  string  `gorm:"column:custom_attr_mobile;comment:图形属性_移动端" json:"custom_attr_mobile"`                                   // 图形属性_移动端
	CustomStyle       string  `gorm:"column:custom_style;comment:组件样式" json:"custom_style"`                                                   // 组件样式
	CustomStyleMobile string  `gorm:"column:custom_style_mobile;comment:组件样式_移动端" json:"custom_style_mobile"`                                 // 组件样式_移动端
	CustomFilter      string  `gorm:"column:custom_filter;comment:结果过滤" json:"custom_filter"`                                                 // 结果过滤
	DrillFields       string  `gorm:"column:drill_fields;comment:钻取字段" json:"drill_fields"`                                                   // 钻取字段
	Senior            string  `gorm:"column:senior;comment:高级" json:"senior"`                                                                 // 高级
	CreateBy          string  `gorm:"column:create_by;comment:创建人ID" json:"create_by"`                                                        // 创建人ID
	CreateTime        int64   `gorm:"column:create_time;comment:创建时间" json:"create_time"`                                                     // 创建时间
	UpdateTime        int64   `gorm:"column:update_time;comment:更新时间" json:"update_time"`                                                     // 更新时间
	Snapshot          string  `gorm:"column:snapshot;comment:缩略图" json:"snapshot"`                                                            // 缩略图
	StylePriority     string  `gorm:"column:style_priority;default:panel;comment:样式优先级 panel 仪表板 view 图表" json:"style_priority"`              // 样式优先级 panel 仪表板 view 图表
	ChartType         string  `gorm:"column:chart_type;default:private;comment:图表类型 public 公共 历史可复用的图表，private 私有 专属某个仪表板" json:"chart_type"` // 图表类型 public 公共 历史可复用的图表，private 私有 专属某个仪表板
	IsPlugin          []uint8 `gorm:"column:is_plugin;comment:是否插件" json:"is_plugin"`                                                         // 是否插件
	DataFrom          string  `gorm:"column:data_from;default:dataset;comment:数据来源 template 模板数据 dataset 数据集数据" json:"data_from"`             // 数据来源 template 模板数据 dataset 数据集数据
	ViewFields        string  `gorm:"column:view_fields;comment:图表字段集合" json:"view_fields"`                                                   // 图表字段集合
	RefreshViewEnable bool    `gorm:"column:refresh_view_enable;comment:是否开启刷新" json:"refresh_view_enable"`                                   // 是否开启刷新
	RefreshUnit       string  `gorm:"column:refresh_unit;default:minute;comment:刷新时间单位" json:"refresh_unit"`                                  // 刷新时间单位
	RefreshTime       int32   `gorm:"column:refresh_time;default:5;comment:刷新时间" json:"refresh_time"`                                         // 刷新时间
	LinkageActive     bool    `gorm:"column:linkage_active;comment:是否开启联动" json:"linkage_active"`                                             // 是否开启联动
	JumpActive        bool    `gorm:"column:jump_active;comment:是否开启跳转" json:"jump_active"`                                                   // 是否开启跳转
	CopyFrom          int64   `gorm:"column:copy_from;comment:复制来源" json:"copy_from"`                                                         // 复制来源
	CopyID            int64   `gorm:"column:copy_id;comment:复制ID" json:"copy_id"`                                                             // 复制ID
	Aggregate         []uint8 `gorm:"column:aggregate;comment:区间条形图开启时间纬度开启聚合" json:"aggregate"`                                              // 区间条形图开启时间纬度开启聚合
	FlowMapStartName  string  `gorm:"column:flow_map_start_name;comment:流向地图起点名称field" json:"flow_map_start_name"`                            // 流向地图起点名称field
	FlowMapEndName    string  `gorm:"column:flow_map_end_name;comment:流向地图终点名称field" json:"flow_map_end_name"`                                // 流向地图终点名称field
	ExtColor          string  `gorm:"column:ext_color;comment:颜色维度field" json:"ext_color"`                                                    // 颜色维度field
	SortPriority      string  `gorm:"column:sort_priority;comment:字段排序优先级" json:"sort_priority"`                                              // 字段排序优先级
}

// TableName CoreChartView's table name
func (*CoreChartView) TableName() string {
	return TableNameCoreChartView
}
