// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package auto

const TableNameCoreCustomGeoSubArea = "core_custom_geo_sub_area"

// CoreCustomGeoSubArea 自定义地理区域分区详情
type CoreCustomGeoSubArea struct {
	ID        int64  `gorm:"column:id;primaryKey;comment:id" json:"id"`                        // id
	Name      string `gorm:"column:name;not null;comment:名称" json:"name"`                      // 名称
	Scope     string `gorm:"column:scope;comment:区域范围" json:"scope"`                           // 区域范围
	GeoAreaID string `gorm:"column:geo_area_id;not null;comment:自定义地理区域id" json:"geo_area_id"` // 自定义地理区域id
}

// TableName CoreCustomGeoSubArea's table name
func (*CoreCustomGeoSubArea) TableName() string {
	return TableNameCoreCustomGeoSubArea
}
