// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package auto

const TableNameDataVisualizationInfo = "data_visualization_info"

// DataVisualizationInfo mapped from table <data_visualization_info>
type DataVisualizationInfo struct {
	ID                  string `gorm:"column:id;primaryKey" json:"id"`
	Name                string `gorm:"column:name;comment:名称" json:"name"`                                                   // 名称
	Pid                 string `gorm:"column:pid;comment:父id" json:"pid"`                                                    // 父id
	OrgID               string `gorm:"column:org_id;comment:所属组织id" json:"org_id"`                                           // 所属组织id
	Level               int32  `gorm:"column:level;comment:层级" json:"level"`                                                 // 层级
	NodeType            string `gorm:"column:node_type;comment:节点类型  folder or panel 目录或者文件夹" json:"node_type"`              // 节点类型  folder or panel 目录或者文件夹
	Type                string `gorm:"column:type;comment:类型" json:"type"`                                                   // 类型
	CanvasStyleData     string `gorm:"column:canvas_style_data;comment:样式数据" json:"canvas_style_data"`                       // 样式数据
	ComponentData       string `gorm:"column:component_data;comment:组件数据" json:"component_data"`                             // 组件数据
	MobileLayout        int32  `gorm:"column:mobile_layout;comment:移动端布局0-关闭 1-开启" json:"mobile_layout"`                     // 移动端布局0-关闭 1-开启
	Status              int32  `gorm:"column:status;default:1;comment:状态 0-未发布 1-已发布" json:"status"`                         // 状态 0-未发布 1-已发布
	SelfWatermarkStatus int32  `gorm:"column:self_watermark_status;comment:是否单独打开水印 0-关闭 1-开启" json:"self_watermark_status"` // 是否单独打开水印 0-关闭 1-开启
	Sort                int32  `gorm:"column:sort;comment:排序" json:"sort"`                                                   // 排序
	CreateTime          int64  `gorm:"column:create_time;comment:创建时间" json:"create_time"`                                   // 创建时间
	CreateBy            string `gorm:"column:create_by;comment:创建人" json:"create_by"`                                        // 创建人
	UpdateTime          int64  `gorm:"column:update_time;comment:更新时间" json:"update_time"`                                   // 更新时间
	UpdateBy            string `gorm:"column:update_by;comment:更新人" json:"update_by"`                                        // 更新人
	Remark              string `gorm:"column:remark;comment:备注" json:"remark"`                                               // 备注
	Source              string `gorm:"column:source;comment:数据来源" json:"source"`                                             // 数据来源
	DeleteFlag          bool   `gorm:"column:delete_flag;comment:删除标志" json:"delete_flag"`                                   // 删除标志
	DeleteTime          int64  `gorm:"column:delete_time;comment:删除时间" json:"delete_time"`                                   // 删除时间
	DeleteBy            string `gorm:"column:delete_by;comment:删除人" json:"delete_by"`                                        // 删除人
	Version             int32  `gorm:"column:version;default:3;comment:可视化资源版本" json:"version"`                              // 可视化资源版本
	ContentID           string `gorm:"column:content_id;comment:内容标识" json:"content_id"`                                     // 内容标识
	CheckVersion        string `gorm:"column:check_version;default:1;comment:内容检查标识" json:"check_version"`                   // 内容检查标识
}

// TableName DataVisualizationInfo's table name
func (*DataVisualizationInfo) TableName() string {
	return TableNameDataVisualizationInfo
}
