// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package auto

import (
	"time"
)

const TableNameDeAuditLogDetail = "de_audit_log_detail"

// DeAuditLogDetail 审计日志详情表
type DeAuditLogDetail struct {
	ID          int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键ID" json:"id"`                                     // 主键ID
	AuditLogID  int64     `gorm:"column:audit_log_id;not null;comment:审计日志主表ID" json:"audit_log_id"`                                  // 审计日志主表ID
	DetailType  string    `gorm:"column:detail_type;comment:详情类型: BEFORE_AFTER, PERMISSION_CHANGE, EXPORT_RECORD" json:"detail_type"` // 详情类型: BEFORE_AFTER, PERMISSION_CHANGE, EXPORT_RECORD
	DetailKey   string    `gorm:"column:detail_key;comment:详情键" json:"detail_key"`                                                    // 详情键
	DetailValue string    `gorm:"column:detail_value;comment:详情值" json:"detail_value"`                                                // 详情值
	CreateTime  time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"`              // 创建时间
}

// TableName DeAuditLogDetail's table name
func (*DeAuditLogDetail) TableName() string {
	return TableNameDeAuditLogDetail
}
