// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package auto

import (
	"time"
)

const TableNameDeAuditLog = "de_audit_log"

// DeAuditLog 审计日志主表
type DeAuditLog struct {
	ID             int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键ID" json:"id"`                                                          // 主键ID
	UserID         int64     `gorm:"column:user_id;comment:操作用户ID" json:"user_id"`                                                                            // 操作用户ID
	Username       string    `gorm:"column:username;comment:操作用户名" json:"username"`                                                                           // 操作用户名
	ActionType     string    `gorm:"column:action_type;not null;comment:操作类型: USER_ACTION, PERMISSION_CHANGE, DATA_ACCESS, SYSTEM_CONFIG" json:"action_type"` // 操作类型: USER_ACTION, PERMISSION_CHANGE, DATA_ACCESS, SYSTEM_CONFIG
	ActionName     string    `gorm:"column:action_name;not null;comment:操作名称: CREATE_USER, DELETE_ROLE, EXPORT_DATA, etc." json:"action_name"`                // 操作名称: CREATE_USER, DELETE_ROLE, EXPORT_DATA, etc.
	ResourceType   string    `gorm:"column:resource_type;comment:资源类型: USER, ORGANIZATION, ROLE, PERMISSION, DATASET, DASHBOARD" json:"resource_type"`        // 资源类型: USER, ORGANIZATION, ROLE, PERMISSION, DATASET, DASHBOARD
	ResourceID     int64     `gorm:"column:resource_id;comment:操作的资源ID" json:"resource_id"`                                                                   // 操作的资源ID
	ResourceName   string    `gorm:"column:resource_name;comment:资源名称" json:"resource_name"`                                                                  // 资源名称
	Operation      string    `gorm:"column:operation;not null;comment:操作类型: CREATE, UPDATE, DELETE, EXPORT, LOGIN, LOGOUT" json:"operation"`                  // 操作类型: CREATE, UPDATE, DELETE, EXPORT, LOGIN, LOGOUT
	Status         string    `gorm:"column:status;not null;default:SUCCESS;comment:操作状态: SUCCESS, FAILED" json:"status"`                                      // 操作状态: SUCCESS, FAILED
	FailureReason  string    `gorm:"column:failure_reason;comment:失败原因" json:"failure_reason"`                                                                // 失败原因
	IPAddress      string    `gorm:"column:ip_address;comment:操作IP地址" json:"ip_address"`                                                                      // 操作IP地址
	UserAgent      string    `gorm:"column:user_agent;comment:用户代理" json:"user_agent"`                                                                        // 用户代理
	BeforeValue    string    `gorm:"column:before_value;comment:操作前的值（JSON格式）" json:"before_value"`                                                           // 操作前的值（JSON格式）
	AfterValue     string    `gorm:"column:after_value;comment:操作后的值（JSON格式）" json:"after_value"`                                                             // 操作后的值（JSON格式）
	OrganizationID int64     `gorm:"column:organization_id;comment:操作时所在的组织ID" json:"organization_id"`                                                        // 操作时所在的组织ID
	CreateTime     time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"`                                   // 创建时间
}

// TableName DeAuditLog's table name
func (*DeAuditLog) TableName() string {
	return TableNameDeAuditLog
}
