// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package auto

import (
	"time"
)

const TableNameDeLoginFailure = "de_login_failure"

// DeLoginFailure 登录失败记录表
type DeLoginFailure struct {
	ID            int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键ID" json:"id"`                        // 主键ID
	Username      string    `gorm:"column:username;not null;comment:尝试登录的用户名" json:"username"`                             // 尝试登录的用户名
	IPAddress     string    `gorm:"column:ip_address;comment:登录IP地址" json:"ip_address"`                                    // 登录IP地址
	FailureReason string    `gorm:"column:failure_reason;comment:失败原因" json:"failure_reason"`                              // 失败原因
	UserAgent     string    `gorm:"column:user_agent;comment:用户代理" json:"user_agent"`                                      // 用户代理
	CreateTime    time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"` // 创建时间
}

// TableName DeLoginFailure's table name
func (*DeLoginFailure) TableName() string {
	return TableNameDeLoginFailure
}
