// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package auto

import (
	"time"
)

const TableNameDeTemplateVersion = "de_template_version"

// DeTemplateVersion dataease模板配置版本记录表
type DeTemplateVersion struct {
	InstalledRank int32     `gorm:"column:installed_rank;primaryKey;comment:主键" json:"installed_rank"`                       // 主键
	Version       string    `gorm:"column:version;comment:版本" json:"version"`                                                // 版本
	Description   string    `gorm:"column:description;comment:描述" json:"description"`                                        // 描述
	Type          string    `gorm:"column:type;comment:类型" json:"type"`                                                      // 类型
	Script        string    `gorm:"column:script;not null;comment:脚本" json:"script"`                                         // 脚本
	Checksum      int32     `gorm:"column:checksum;comment:CheckSum校验码" json:"checksum"`                                     // CheckSum校验码
	InstalledBy   string    `gorm:"column:installed_by;comment:安装人" json:"installed_by"`                                     // 安装人
	InstalledOn   time.Time `gorm:"column:installed_on;not null;default:CURRENT_TIMESTAMP;comment:安装时间" json:"installed_on"` // 安装时间
	ExecutionTime int32     `gorm:"column:execution_time;comment:执行时间" json:"execution_time"`                                // 执行时间
	Success       bool      `gorm:"column:success;not null;comment:执行状态" json:"success"`                                     // 执行状态
}

// TableName DeTemplateVersion's table name
func (*DeTemplateVersion) TableName() string {
	return TableNameDeTemplateVersion
}
