// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package auto

const TableNameQRTZFIREDTRIGGER = "QRTZ_FIRED_TRIGGERS"

// QRTZFIREDTRIGGER mapped from table <QRTZ_FIRED_TRIGGERS>
type QRTZFIREDTRIGGER struct {
	SCHEDNAME        string `gorm:"column:SCHED_NAME;primaryKey" json:"SCHED_NAME"`
	ENTRYID          string `gorm:"column:ENTRY_ID;primaryKey" json:"ENTRY_ID"`
	TRIGGERNAME      string `gorm:"column:TRIGGER_NAME;not null" json:"TRIGGER_NAME"`
	TRIGGERGROUP     string `gorm:"column:TRIGGER_GROUP;not null" json:"TRIGGER_GROUP"`
	INSTANCENAME     string `gorm:"column:INSTANCE_NAME;not null" json:"INSTANCE_NAME"`
	FIREDTIME        int64  `gorm:"column:FIRED_TIME;not null" json:"FIRED_TIME"`
	SCHEDTIME        int64  `gorm:"column:SCHED_TIME;not null" json:"SCHED_TIME"`
	PRIORITY         int32  `gorm:"column:PRIORITY;not null" json:"PRIORITY"`
	STATE            string `gorm:"column:STATE;not null" json:"STATE"`
	JOBNAME          string `gorm:"column:JOB_NAME" json:"JOB_NAME"`
	JOBGROUP         string `gorm:"column:JOB_GROUP" json:"JOB_GROUP"`
	ISNONCONCURRENT  string `gorm:"column:IS_NONCONCURRENT" json:"IS_NONCONCURRENT"`
	REQUESTSRECOVERY string `gorm:"column:REQUESTS_RECOVERY" json:"REQUESTS_RECOVERY"`
}

// TableName QRTZFIREDTRIGGER's table name
func (*QRTZFIREDTRIGGER) TableName() string {
	return TableNameQRTZFIREDTRIGGER
}
