// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package auto

const TableNameQRTZCALENDAR = "QRTZ_CALENDARS"

// QRTZCALENDAR mapped from table <QRTZ_CALENDARS>
type QRTZCALENDAR struct {
	SCHEDNAME    string `gorm:"column:SCHED_NAME;primaryKey" json:"SCHED_NAME"`
	CALENDARNAME string `gorm:"column:CALENDAR_NAME;primaryKey" json:"CALENDAR_NAME"`
	CALENDAR     []byte `gorm:"column:CALENDAR;not null" json:"CALENDAR"`
}

// TableName QRTZCALENDAR's table name
func (*QRTZCALENDAR) TableName() string {
	return TableNameQRTZCALENDAR
}
