// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package auto

const TableNameQRTZPAUSEDTRIGGERGRP = "QRTZ_PAUSED_TRIGGER_GRPS"

// QRTZPAUSEDTRIGGERGRP mapped from table <QRTZ_PAUSED_TRIGGER_GRPS>
type QRTZPAUSEDTRIGGERGRP struct {
	SCHEDNAME    string `gorm:"column:SCHED_NAME;primaryKey" json:"SCHED_NAME"`
	TRIGGERGROUP string `gorm:"column:TRIGGER_GROUP;primaryKey" json:"TRIGGER_GROUP"`
}

// TableName QRTZPAUSEDTRIGGERGRP's table name
func (*QRTZPAUSEDTRIGGERGRP) TableName() string {
	return TableNameQRTZPAUSEDTRIGGERGRP
}
