// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package auto

const TableNameQRTZSIMPLETRIGGER = "QRTZ_SIMPLE_TRIGGERS"

// QRTZSIMPLETRIGGER mapped from table <QRTZ_SIMPLE_TRIGGERS>
type QRTZSIMPLETRIGGER struct {
	SCHEDNAME      string `gorm:"column:SCHED_NAME;primaryKey" json:"SCHED_NAME"`
	TRIGGERNAME    string `gorm:"column:TRIGGER_NAME;primaryKey" json:"TRIGGER_NAME"`
	TRIGGERGROUP   string `gorm:"column:TRIGGER_GROUP;primaryKey" json:"TRIGGER_GROUP"`
	REPEATCOUNT    int64  `gorm:"column:REPEAT_COUNT;not null" json:"REPEAT_COUNT"`
	REPEATINTERVAL int64  `gorm:"column:REPEAT_INTERVAL;not null" json:"REPEAT_INTERVAL"`
	TIMESTRIGGERED int64  `gorm:"column:TIMES_TRIGGERED;not null" json:"TIMES_TRIGGERED"`
}

// TableName QRTZSIMPLETRIGGER's table name
func (*QRTZSIMPLETRIGGER) TableName() string {
	return TableNameQRTZSIMPLETRIGGER
}
