// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package auto

const TableNameQRTZJOBDETAIL = "QRTZ_JOB_DETAILS"

// QRTZJOBDETAIL mapped from table <QRTZ_JOB_DETAILS>
type QRTZJOBDETAIL struct {
	SCHEDNAME        string `gorm:"column:SCHED_NAME;primaryKey" json:"SCHED_NAME"`
	JOBNAME          string `gorm:"column:JOB_NAME;primaryKey" json:"JOB_NAME"`
	JOBGROUP         string `gorm:"column:JOB_GROUP;primaryKey" json:"JOB_GROUP"`
	DESCRIPTION      string `gorm:"column:DESCRIPTION" json:"DESCRIPTION"`
	JOBCLASSNAME     string `gorm:"column:JOB_CLASS_NAME;not null" json:"JOB_CLASS_NAME"`
	ISDURABLE        string `gorm:"column:IS_DURABLE;not null" json:"IS_DURABLE"`
	ISNONCONCURRENT  string `gorm:"column:IS_NONCONCURRENT;not null" json:"IS_NONCONCURRENT"`
	ISUPDATEDATA     string `gorm:"column:IS_UPDATE_DATA;not null" json:"IS_UPDATE_DATA"`
	REQUESTSRECOVERY string `gorm:"column:REQUESTS_RECOVERY;not null" json:"REQUESTS_RECOVERY"`
	JOBDATA          []byte `gorm:"column:JOB_DATA" json:"JOB_DATA"`
}

// TableName QRTZJOBDETAIL's table name
func (*QRTZJOBDETAIL) TableName() string {
	return TableNameQRTZJOBDETAIL
}
