// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package auto

const TableNameQRTZLOCK = "QRTZ_LOCKS"

// QRTZLOCK mapped from table <QRTZ_LOCKS>
type QRTZLOCK struct {
	SCHEDNAME string `gorm:"column:SCHED_NAME;primaryKey" json:"SCHED_NAME"`
	LOCKNAME  string `gorm:"column:LOCK_NAME;primaryKey" json:"LOCK_NAME"`
}

// TableName QRTZLOCK's table name
func (*QRTZLOCK) TableName() string {
	return TableNameQRTZLOCK
}
