// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package auto

const TableNameQRTZTRIGGER = "QRTZ_TRIGGERS"

// QRTZTRIGGER mapped from table <QRTZ_TRIGGERS>
type QRTZTRIGGER struct {
	SCHEDNAME    string `gorm:"column:SCHED_NAME;primaryKey" json:"SCHED_NAME"`
	TRIGGERNAME  string `gorm:"column:TRIGGER_NAME;primaryKey" json:"TRIGGER_NAME"`
	TRIGGERGROUP string `gorm:"column:TRIGGER_GROUP;primaryKey" json:"TRIGGER_GROUP"`
	JOBNAME      string `gorm:"column:JOB_NAME;not null" json:"JOB_NAME"`
	JOBGROUP     string `gorm:"column:JOB_GROUP;not null" json:"JOB_GROUP"`
	DESCRIPTION  string `gorm:"column:DESCRIPTION" json:"DESCRIPTION"`
	NEXTFIRETIME int64  `gorm:"column:NEXT_FIRE_TIME" json:"NEXT_FIRE_TIME"`
	PREVFIRETIME int64  `gorm:"column:PREV_FIRE_TIME" json:"PREV_FIRE_TIME"`
	PRIORITY     int32  `gorm:"column:PRIORITY" json:"PRIORITY"`
	TRIGGERSTATE string `gorm:"column:TRIGGER_STATE;not null" json:"TRIGGER_STATE"`
	TRIGGERTYPE  string `gorm:"column:TRIGGER_TYPE;not null" json:"TRIGGER_TYPE"`
	STARTTIME    int64  `gorm:"column:START_TIME;not null" json:"START_TIME"`
	ENDTIME      int64  `gorm:"column:END_TIME" json:"END_TIME"`
	CALENDARNAME string `gorm:"column:CALENDAR_NAME" json:"CALENDAR_NAME"`
	MISFIREINSTR int32  `gorm:"column:MISFIRE_INSTR" json:"MISFIRE_INSTR"`
	JOBDATA      []byte `gorm:"column:JOB_DATA" json:"JOB_DATA"`
}

// TableName QRTZTRIGGER's table name
func (*QRTZTRIGGER) TableName() string {
	return TableNameQRTZTRIGGER
}
