// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package auto

const TableNameQRTZSIMPROPTRIGGER = "QRTZ_SIMPROP_TRIGGERS"

// QRTZSIMPROPTRIGGER mapped from table <QRTZ_SIMPROP_TRIGGERS>
type QRTZSIMPROPTRIGGER struct {
	SCHEDNAME    string  `gorm:"column:SCHED_NAME;primaryKey" json:"SCHED_NAME"`
	TRIGGERNAME  string  `gorm:"column:TRIGGER_NAME;primaryKey" json:"TRIGGER_NAME"`
	TRIGGERGROUP string  `gorm:"column:TRIGGER_GROUP;primaryKey" json:"TRIGGER_GROUP"`
	STRPROP1     string  `gorm:"column:STR_PROP_1" json:"STR_PROP_1"`
	STRPROP2     string  `gorm:"column:STR_PROP_2" json:"STR_PROP_2"`
	STRPROP3     string  `gorm:"column:STR_PROP_3" json:"STR_PROP_3"`
	INTPROP1     int32   `gorm:"column:INT_PROP_1" json:"INT_PROP_1"`
	INTPROP2     int32   `gorm:"column:INT_PROP_2" json:"INT_PROP_2"`
	LONGPROP1    int64   `gorm:"column:LONG_PROP_1" json:"LONG_PROP_1"`
	LONGPROP2    int64   `gorm:"column:LONG_PROP_2" json:"LONG_PROP_2"`
	DECPROP1     float64 `gorm:"column:DEC_PROP_1" json:"DEC_PROP_1"`
	DECPROP2     float64 `gorm:"column:DEC_PROP_2" json:"DEC_PROP_2"`
	BOOLPROP1    string  `gorm:"column:BOOL_PROP_1" json:"BOOL_PROP_1"`
	BOOLPROP2    string  `gorm:"column:BOOL_PROP_2" json:"BOOL_PROP_2"`
}

// TableName QRTZSIMPROPTRIGGER's table name
func (*QRTZSIMPROPTRIGGER) TableName() string {
	return TableNameQRTZSIMPROPTRIGGER
}
