// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package auto

const TableNameQRTZBLOBTRIGGER = "QRTZ_BLOB_TRIGGERS"

// QRTZBLOBTRIGGER mapped from table <QRTZ_BLOB_TRIGGERS>
type QRTZBLOBTRIGGER struct {
	SCHEDNAME    string `gorm:"column:SCHED_NAME;primaryKey" json:"SCHED_NAME"`
	TRIGGERNAME  string `gorm:"column:TRIGGER_NAME;primaryKey" json:"TRIGGER_NAME"`
	TRIGGERGROUP string `gorm:"column:TRIGGER_GROUP;primaryKey" json:"TRIGGER_GROUP"`
	BLOBDATA     []byte `gorm:"column:BLOB_DATA" json:"BLOB_DATA"`
}

// TableName QRTZBLOBTRIGGER's table name
func (*QRTZBLOBTRIGGER) TableName() string {
	return TableNameQRTZBLOBTRIGGER
}
