// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package auto

const TableNameQRTZSCHEDULERSTATE = "QRTZ_SCHEDULER_STATE"

// QRTZSCHEDULERSTATE mapped from table <QRTZ_SCHEDULER_STATE>
type QRTZSCHEDULERSTATE struct {
	SCHEDNAME       string `gorm:"column:SCHED_NAME;primaryKey" json:"SCHED_NAME"`
	INSTANCENAME    string `gorm:"column:INSTANCE_NAME;primaryKey" json:"INSTANCE_NAME"`
	LASTCHECKINTIME int64  `gorm:"column:LAST_CHECKIN_TIME;not null" json:"LAST_CHECKIN_TIME"`
	CHECKININTERVAL int64  `gorm:"column:CHECKIN_INTERVAL;not null" json:"CHECKIN_INTERVAL"`
}

// TableName QRTZSCHEDULERSTATE's table name
func (*QRTZSCHEDULERSTATE) TableName() string {
	return TableNameQRTZSCHEDULERSTATE
}
