// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package auto

const TableNameQRTZCRONTRIGGER = "QRTZ_CRON_TRIGGERS"

// QRTZCRONTRIGGER mapped from table <QRTZ_CRON_TRIGGERS>
type QRTZCRONTRIGGER struct {
	SCHEDNAME      string `gorm:"column:SCHED_NAME;primaryKey" json:"SCHED_NAME"`
	TRIGGERNAME    string `gorm:"column:TRIGGER_NAME;primaryKey" json:"TRIGGER_NAME"`
	TRIGGERGROUP   string `gorm:"column:TRIGGER_GROUP;primaryKey" json:"TRIGGER_GROUP"`
	CRONEXPRESSION string `gorm:"column:CRON_EXPRESSION;not null" json:"CRON_EXPRESSION"`
	TIMEZONEID     string `gorm:"column:TIME_ZONE_ID" json:"TIME_ZONE_ID"`
}

// TableName QRTZCRONTRIGGER's table name
func (*QRTZCRONTRIGGER) TableName() string {
	return TableNameQRTZCRONTRIGGER
}
