// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package auto

const TableNameSnapshotVisualizationOuterParamsTargetViewInfo = "snapshot_visualization_outer_params_target_view_info"

// SnapshotVisualizationOuterParamsTargetViewInfo mapped from table <snapshot_visualization_outer_params_target_view_info>
type SnapshotVisualizationOuterParamsTargetViewInfo struct {
	TargetID      string `gorm:"column:target_id;primaryKey;comment:主键" json:"target_id"`                                   // 主键
	ParamsInfoID  string `gorm:"column:params_info_id;comment:visualization_outer_params_info 表的 ID" json:"params_info_id"` // visualization_outer_params_info 表的 ID
	TargetViewID  string `gorm:"column:target_view_id;comment:联动视图ID/联动过滤项ID" json:"target_view_id"`                        // 联动视图ID/联动过滤项ID
	TargetFieldID string `gorm:"column:target_field_id;comment:联动字段ID" json:"target_field_id"`                              // 联动字段ID
	CopyFrom      string `gorm:"column:copy_from;comment:复制来源" json:"copy_from"`                                            // 复制来源
	CopyID        string `gorm:"column:copy_id;comment:复制来源ID" json:"copy_id"`                                              // 复制来源ID
	TargetDsID    string `gorm:"column:target_ds_id;comment:联动数据集id/联动过滤组件id" json:"target_ds_id"`                          // 联动数据集id/联动过滤组件id
}

// TableName SnapshotVisualizationOuterParamsTargetViewInfo's table name
func (*SnapshotVisualizationOuterParamsTargetViewInfo) TableName() string {
	return TableNameSnapshotVisualizationOuterParamsTargetViewInfo
}
