// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package auto

const TableNameSnapshotVisualizationLinkage = "snapshot_visualization_linkage"

// SnapshotVisualizationLinkage mapped from table <snapshot_visualization_linkage>
type SnapshotVisualizationLinkage struct {
	ID            int64  `gorm:"column:id;primaryKey;comment:主键" json:"id"`                  // 主键
	DvID          int64  `gorm:"column:dv_id;comment:联动大屏/仪表板ID" json:"dv_id"`               // 联动大屏/仪表板ID
	SourceViewID  int64  `gorm:"column:source_view_id;comment:源图表id" json:"source_view_id"`  // 源图表id
	TargetViewID  int64  `gorm:"column:target_view_id;comment:联动图表id" json:"target_view_id"` // 联动图表id
	UpdateTime    int64  `gorm:"column:update_time;comment:更新时间" json:"update_time"`         // 更新时间
	UpdatePeople  string `gorm:"column:update_people;comment:更新人" json:"update_people"`      // 更新人
	LinkageActive bool   `gorm:"column:linkage_active;comment:是否启用关联" json:"linkage_active"` // 是否启用关联
	Ext1          string `gorm:"column:ext1;comment:扩展字段1" json:"ext1"`                      // 扩展字段1
	Ext2          string `gorm:"column:ext2;comment:扩展字段2" json:"ext2"`                      // 扩展字段2
	CopyFrom      int64  `gorm:"column:copy_from;comment:复制来源" json:"copy_from"`             // 复制来源
	CopyID        int64  `gorm:"column:copy_id;comment:复制来源ID" json:"copy_id"`               // 复制来源ID
}

// TableName SnapshotVisualizationLinkage's table name
func (*SnapshotVisualizationLinkage) TableName() string {
	return TableNameSnapshotVisualizationLinkage
}
