// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package auto

const TableNameSnapshotVisualizationLinkJump = "snapshot_visualization_link_jump"

// SnapshotVisualizationLinkJump mapped from table <snapshot_visualization_link_jump>
type SnapshotVisualizationLinkJump struct {
	ID           int64  `gorm:"column:id;primaryKey;comment:主键" json:"id"`                 // 主键
	SourceDvID   int64  `gorm:"column:source_dv_id;comment:源仪表板ID" json:"source_dv_id"`    // 源仪表板ID
	SourceViewID int64  `gorm:"column:source_view_id;comment:源图表ID" json:"source_view_id"` // 源图表ID
	LinkJumpInfo string `gorm:"column:link_jump_info;comment:跳转信息" json:"link_jump_info"`  // 跳转信息
	Checked      bool   `gorm:"column:checked;comment:是否启用" json:"checked"`                // 是否启用
	CopyFrom     int64  `gorm:"column:copy_from;comment:复制来源" json:"copy_from"`            // 复制来源
	CopyID       int64  `gorm:"column:copy_id;comment:复制来源ID" json:"copy_id"`              // 复制来源ID
}

// TableName SnapshotVisualizationLinkJump's table name
func (*SnapshotVisualizationLinkJump) TableName() string {
	return TableNameSnapshotVisualizationLinkJump
}
