// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package auto

const TableNameSnapshotVisualizationLinkageField = "snapshot_visualization_linkage_field"

// SnapshotVisualizationLinkageField mapped from table <snapshot_visualization_linkage_field>
type SnapshotVisualizationLinkageField struct {
	ID          int64 `gorm:"column:id;primaryKey;comment:主键" json:"id"`              // 主键
	LinkageID   int64 `gorm:"column:linkage_id;comment:联动ID" json:"linkage_id"`       // 联动ID
	SourceField int64 `gorm:"column:source_field;comment:源图表字段" json:"source_field"`  // 源图表字段
	TargetField int64 `gorm:"column:target_field;comment:目标图表字段" json:"target_field"` // 目标图表字段
	UpdateTime  int64 `gorm:"column:update_time;comment:更新时间" json:"update_time"`     // 更新时间
	CopyFrom    int64 `gorm:"column:copy_from;comment:复制来源" json:"copy_from"`         // 复制来源
	CopyID      int64 `gorm:"column:copy_id;comment:复制来源ID" json:"copy_id"`           // 复制来源ID
}

// TableName SnapshotVisualizationLinkageField's table name
func (*SnapshotVisualizationLinkageField) TableName() string {
	return TableNameSnapshotVisualizationLinkageField
}
