// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package auto

const TableNameSnapshotVisualizationLinkJumpTargetViewInfo = "snapshot_visualization_link_jump_target_view_info"

// SnapshotVisualizationLinkJumpTargetViewInfo mapped from table <snapshot_visualization_link_jump_target_view_info>
type SnapshotVisualizationLinkJumpTargetViewInfo struct {
	TargetID            int64  `gorm:"column:target_id;primaryKey;comment:主键" json:"target_id"`                                              // 主键
	LinkJumpInfoID      int64  `gorm:"column:link_jump_info_id;comment:visualization_link_jump_info 表的 ID" json:"link_jump_info_id"`         // visualization_link_jump_info 表的 ID
	SourceFieldActiveID int64  `gorm:"column:source_field_active_id;comment:勾选字段设置的匹配字段，也可以不是勾选字段本身" json:"source_field_active_id"`          // 勾选字段设置的匹配字段，也可以不是勾选字段本身
	TargetViewID        string `gorm:"column:target_view_id;comment:目标图表ID" json:"target_view_id"`                                           // 目标图表ID
	TargetFieldID       string `gorm:"column:target_field_id;comment:目标字段ID" json:"target_field_id"`                                         // 目标字段ID
	CopyFrom            int64  `gorm:"column:copy_from;comment:复制来源" json:"copy_from"`                                                       // 复制来源
	CopyID              int64  `gorm:"column:copy_id;comment:复制来源ID" json:"copy_id"`                                                         // 复制来源ID
	TargetType          string `gorm:"column:target_type;default:view;comment:联动目标类型 view 图表 filter 过滤组件 outParams 外部参数" json:"target_type"` // 联动目标类型 view 图表 filter 过滤组件 outParams 外部参数
}

// TableName SnapshotVisualizationLinkJumpTargetViewInfo's table name
func (*SnapshotVisualizationLinkJumpTargetViewInfo) TableName() string {
	return TableNameSnapshotVisualizationLinkJumpTargetViewInfo
}
