// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package auto

const TableNameSnapshotVisualizationOuterParamsInfo = "snapshot_visualization_outer_params_info"

// SnapshotVisualizationOuterParamsInfo mapped from table <snapshot_visualization_outer_params_info>
type SnapshotVisualizationOuterParamsInfo struct {
	ParamsInfoID   string `gorm:"column:params_info_id;primaryKey;comment:主键" json:"params_info_id"`          // 主键
	ParamsID       string `gorm:"column:params_id;comment:visualization_outer_params 表的 ID" json:"params_id"` // visualization_outer_params 表的 ID
	ParamName      string `gorm:"column:param_name;comment:参数名" json:"param_name"`                            // 参数名
	Checked        bool   `gorm:"column:checked;comment:是否启用" json:"checked"`                                 // 是否启用
	CopyFrom       string `gorm:"column:copy_from;comment:复制来源" json:"copy_from"`                             // 复制来源
	CopyID         string `gorm:"column:copy_id;comment:复制来源ID" json:"copy_id"`                               // 复制来源ID
	Required       bool   `gorm:"column:required;comment:是否必填" json:"required"`                               // 是否必填
	DefaultValue   string `gorm:"column:default_value;comment:默认值 JSON格式" json:"default_value"`               // 默认值 JSON格式
	EnabledDefault bool   `gorm:"column:enabled_default;comment:是否启用默认值" json:"enabled_default"`              // 是否启用默认值
}

// TableName SnapshotVisualizationOuterParamsInfo's table name
func (*SnapshotVisualizationOuterParamsInfo) TableName() string {
	return TableNameSnapshotVisualizationOuterParamsInfo
}
