// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package auto

const TableNameVisualizationTemplate = "visualization_template"

// VisualizationTemplate 模板表
type VisualizationTemplate struct {
	ID            string `gorm:"column:id;primaryKey;comment:主键" json:"id"`                                    // 主键
	Name          string `gorm:"column:name;comment:名称" json:"name"`                                           // 名称
	Pid           string `gorm:"column:pid;comment:父级id" json:"pid"`                                           // 父级id
	Level         int32  `gorm:"column:level;comment:层级" json:"level"`                                         // 层级
	DvType        string `gorm:"column:dv_type;comment:模板种类  dataV or dashboard 目录或者文件夹" json:"dv_type"`       // 模板种类  dataV or dashboard 目录或者文件夹
	NodeType      string `gorm:"column:node_type;comment:节点类型  app or template 应用 或者 模板" json:"node_type"`     // 节点类型  app or template 应用 或者 模板
	CreateBy      string `gorm:"column:create_by;comment:创建人" json:"create_by"`                                // 创建人
	CreateTime    int64  `gorm:"column:create_time;comment:创建时间" json:"create_time"`                           // 创建时间
	Snapshot      string `gorm:"column:snapshot;comment:缩略图" json:"snapshot"`                                  // 缩略图
	TemplateType  string `gorm:"column:template_type;comment:模板类型 system 系统内置 self 用户自建" json:"template_type"` // 模板类型 system 系统内置 self 用户自建
	TemplateStyle string `gorm:"column:template_style;comment:template 样式" json:"template_style"`              // template 样式
	TemplateData  string `gorm:"column:template_data;comment:template 数据" json:"template_data"`                // template 数据
	DynamicData   string `gorm:"column:dynamic_data;comment:预存数据" json:"dynamic_data"`                         // 预存数据
	AppData       string `gorm:"column:app_data;comment:app数据" json:"app_data"`                                // app数据
	UseCount      int32  `gorm:"column:use_count;comment:使用次数" json:"use_count"`                               // 使用次数
	Version       int32  `gorm:"column:version;default:3;comment:使用资源的版本" json:"version"`                      // 使用资源的版本
}

// TableName VisualizationTemplate's table name
func (*VisualizationTemplate) TableName() string {
	return TableNameVisualizationTemplate
}
