// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package auto

const TableNameVisualizationTemplateCategory = "visualization_template_category"

// VisualizationTemplateCategory 模板表
type VisualizationTemplateCategory struct {
	ID           string `gorm:"column:id;primaryKey;comment:主键" json:"id"`                               // 主键
	Name         string `gorm:"column:name;comment:名称" json:"name"`                                      // 名称
	Pid          string `gorm:"column:pid;comment:父级id" json:"pid"`                                      // 父级id
	Level        int32  `gorm:"column:level;comment:层级" json:"level"`                                    // 层级
	DvType       string `gorm:"column:dv_type;comment:模板种类  dataV or dashboard 目录或者文件夹" json:"dv_type"`  // 模板种类  dataV or dashboard 目录或者文件夹
	NodeType     string `gorm:"column:node_type;comment:节点类型  folder or panel 目录或者文件夹" json:"node_type"` // 节点类型  folder or panel 目录或者文件夹
	CreateBy     string `gorm:"column:create_by;comment:创建人" json:"create_by"`                           // 创建人
	CreateTime   int64  `gorm:"column:create_time;comment:创建时间" json:"create_time"`                      // 创建时间
	Snapshot     string `gorm:"column:snapshot;comment:缩略图" json:"snapshot"`                             // 缩略图
	TemplateType string `gorm:"column:template_type" json:"template_type"`
}

// TableName VisualizationTemplateCategory's table name
func (*VisualizationTemplateCategory) TableName() string {
	return TableNameVisualizationTemplateCategory
}
