// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package auto

const TableNameVisualizationSubject = "visualization_subject"

// VisualizationSubject mapped from table <visualization_subject>
type VisualizationSubject struct {
	ID         string `gorm:"column:id;primaryKey;comment:主键" json:"id"`                   // 主键
	Name       string `gorm:"column:name;comment:主题名称" json:"name"`                        // 主题名称
	Type       string `gorm:"column:type;comment:主题类型 system 系统主题，self 自定义主题" json:"type"` // 主题类型 system 系统主题，self 自定义主题
	Details    string `gorm:"column:details;comment:主题内容" json:"details"`                  // 主题内容
	DeleteFlag bool   `gorm:"column:delete_flag;comment:删除标记" json:"delete_flag"`          // 删除标记
	CoverURL   string `gorm:"column:cover_url;comment:封面信息" json:"cover_url"`              // 封面信息
	CreateNum  int32  `gorm:"column:create_num;not null" json:"create_num"`
	CreateTime int64  `gorm:"column:create_time;comment:创建时间" json:"create_time"` // 创建时间
	CreateBy   string `gorm:"column:create_by;comment:创建人" json:"create_by"`      // 创建人
	UpdateTime int64  `gorm:"column:update_time;comment:更新时间" json:"update_time"` // 更新时间
	UpdateBy   string `gorm:"column:update_by;comment:更新人" json:"update_by"`      // 更新人
	DeleteTime int64  `gorm:"column:delete_time;comment:删除时间" json:"delete_time"` // 删除时间
	DeleteBy   int64  `gorm:"column:delete_by;comment:删除人" json:"delete_by"`      // 删除人
}

// TableName VisualizationSubject's table name
func (*VisualizationSubject) TableName() string {
	return TableNameVisualizationSubject
}
