// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package auto

const TableNameVisualizationWatermark = "visualization_watermark"

// VisualizationWatermark 仪表板水印设置表
type VisualizationWatermark struct {
	ID             string `gorm:"column:id;primaryKey;comment:主键" json:"id"`                  // 主键
	Version        string `gorm:"column:version;comment:版本号" json:"version"`                  // 版本号
	SettingContent string `gorm:"column:setting_content;comment:设置内容" json:"setting_content"` // 设置内容
	CreateBy       string `gorm:"column:create_by;comment:创建人" json:"create_by"`              // 创建人
	CreateTime     int64  `gorm:"column:create_time;comment:创建时间" json:"create_time"`         // 创建时间
}

// TableName VisualizationWatermark's table name
func (*VisualizationWatermark) TableName() string {
	return TableNameVisualizationWatermark
}
