// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package auto

const TableNameVisualizationLinkJumpInfo = "visualization_link_jump_info"

// VisualizationLinkJumpInfo mapped from table <visualization_link_jump_info>
type VisualizationLinkJumpInfo struct {
	ID            int64  `gorm:"column:id;primaryKey" json:"id"`
	LinkJumpID    int64  `gorm:"column:link_jump_id;comment:link jump ID" json:"link_jump_id"`          // link jump ID
	LinkType      string `gorm:"column:link_type;comment:关联类型 inner 内部仪表板，outer 外部链接" json:"link_type"` // 关联类型 inner 内部仪表板，outer 外部链接
	JumpType      string `gorm:"column:jump_type;comment:跳转类型 _blank 新开页面 _self 当前窗口" json:"jump_type"` // 跳转类型 _blank 新开页面 _self 当前窗口
	TargetDvID    int64  `gorm:"column:target_dv_id;comment:关联仪表板ID" json:"target_dv_id"`               // 关联仪表板ID
	SourceFieldID int64  `gorm:"column:source_field_id;comment:字段ID" json:"source_field_id"`            // 字段ID
	Content       string `gorm:"column:content;comment:内容 linkType = outer时使用" json:"content"`          // 内容 linkType = outer时使用
	Checked       bool   `gorm:"column:checked;comment:是否可用" json:"checked"`                            // 是否可用
	AttachParams  bool   `gorm:"column:attach_params;comment:是否附加点击参数" json:"attach_params"`            // 是否附加点击参数
	CopyFrom      int64  `gorm:"column:copy_from" json:"copy_from"`
	CopyID        int64  `gorm:"column:copy_id" json:"copy_id"`
	WindowSize    string `gorm:"column:window_size;default:middle;comment:窗口大小large middle small" json:"window_size"` // 窗口大小large middle small
}

// TableName VisualizationLinkJumpInfo's table name
func (*VisualizationLinkJumpInfo) TableName() string {
	return TableNameVisualizationLinkJumpInfo
}
