// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package auto

const TableNameVisualizationOuterParam = "visualization_outer_params"

// VisualizationOuterParam 外部参数关联关系表
type VisualizationOuterParam struct {
	ParamsID        string `gorm:"column:params_id;primaryKey;comment:主键" json:"params_id"`         // 主键
	VisualizationID string `gorm:"column:visualization_id;comment:可视化资源ID" json:"visualization_id"` // 可视化资源ID
	Checked         bool   `gorm:"column:checked;comment:是否启用外部参数标识（1-是，0-否）" json:"checked"`       // 是否启用外部参数标识（1-是，0-否）
	Remark          string `gorm:"column:remark;comment:备注" json:"remark"`                          // 备注
	CopyFrom        string `gorm:"column:copy_from;comment:复制来源" json:"copy_from"`                  // 复制来源
	CopyID          string `gorm:"column:copy_id;comment:复制来源ID" json:"copy_id"`                    // 复制来源ID
}

// TableName VisualizationOuterParam's table name
func (*VisualizationOuterParam) TableName() string {
	return TableNameVisualizationOuterParam
}
