// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package auto

const TableNameVisualizationLinkageField = "visualization_linkage_field"

// VisualizationLinkageField mapped from table <visualization_linkage_field>
type VisualizationLinkageField struct {
	ID          int64 `gorm:"column:id;primaryKey" json:"id"`
	LinkageID   int64 `gorm:"column:linkage_id;comment:联动ID" json:"linkage_id"`       // 联动ID
	SourceField int64 `gorm:"column:source_field;comment:源图表字段" json:"source_field"`  // 源图表字段
	TargetField int64 `gorm:"column:target_field;comment:目标图表字段" json:"target_field"` // 目标图表字段
	UpdateTime  int64 `gorm:"column:update_time;comment:更新时间" json:"update_time"`     // 更新时间
	CopyFrom    int64 `gorm:"column:copy_from" json:"copy_from"`
	CopyID      int64 `gorm:"column:copy_id" json:"copy_id"`
}

// TableName VisualizationLinkageField's table name
func (*VisualizationLinkageField) TableName() string {
	return TableNameVisualizationLinkageField
}
