// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package auto

const TableNameVisualizationLinkage = "visualization_linkage"

// VisualizationLinkage mapped from table <visualization_linkage>
type VisualizationLinkage struct {
	ID            int64  `gorm:"column:id;primaryKey" json:"id"`
	DvID          int64  `gorm:"column:dv_id" json:"dv_id"`
	SourceViewID  int64  `gorm:"column:source_view_id;comment:源图表id" json:"source_view_id"`  // 源图表id
	TargetViewID  int64  `gorm:"column:target_view_id;comment:联动图表id" json:"target_view_id"` // 联动图表id
	UpdateTime    int64  `gorm:"column:update_time;comment:更新时间" json:"update_time"`         // 更新时间
	UpdatePeople  string `gorm:"column:update_people;comment:更新人" json:"update_people"`      // 更新人
	LinkageActive bool   `gorm:"column:linkage_active;comment:是否启用关联" json:"linkage_active"` // 是否启用关联
	Ext1          string `gorm:"column:ext1" json:"ext1"`
	Ext2          string `gorm:"column:ext2" json:"ext2"`
	CopyFrom      int64  `gorm:"column:copy_from" json:"copy_from"`
	CopyID        int64  `gorm:"column:copy_id" json:"copy_id"`
}

// TableName VisualizationLinkage's table name
func (*VisualizationLinkage) TableName() string {
	return TableNameVisualizationLinkage
}
