// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package auto

const TableNameVisualizationLinkJump = "visualization_link_jump"

// VisualizationLinkJump mapped from table <visualization_link_jump>
type VisualizationLinkJump struct {
	ID           int64  `gorm:"column:id;primaryKey" json:"id"`
	SourceDvID   int64  `gorm:"column:source_dv_id;comment:源仪表板ID" json:"source_dv_id"`    // 源仪表板ID
	SourceViewID int64  `gorm:"column:source_view_id;comment:源图表ID" json:"source_view_id"` // 源图表ID
	LinkJumpInfo string `gorm:"column:link_jump_info;comment:跳转信息" json:"link_jump_info"`  // 跳转信息
	Checked      bool   `gorm:"column:checked;comment:是否启用" json:"checked"`                // 是否启用
	CopyFrom     int64  `gorm:"column:copy_from" json:"copy_from"`
	CopyID       int64  `gorm:"column:copy_id" json:"copy_id"`
}

// TableName VisualizationLinkJump's table name
func (*VisualizationLinkJump) TableName() string {
	return TableNameVisualizationLinkJump
}
