// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package auto

const TableNameVisualizationTemplateExtendDatum = "visualization_template_extend_data"

// VisualizationTemplateExtendDatum mapped from table <visualization_template_extend_data>
type VisualizationTemplateExtendDatum struct {
	ID          int64  `gorm:"column:id;primaryKey" json:"id"`
	DvID        int64  `gorm:"column:dv_id" json:"dv_id"`
	ViewID      int64  `gorm:"column:view_id" json:"view_id"`
	ViewDetails string `gorm:"column:view_details" json:"view_details"`
	CopyFrom    string `gorm:"column:copy_from" json:"copy_from"`
	CopyID      string `gorm:"column:copy_id" json:"copy_id"`
}

// TableName VisualizationTemplateExtendDatum's table name
func (*VisualizationTemplateExtendDatum) TableName() string {
	return TableNameVisualizationTemplateExtendDatum
}
