// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package auto

const TableNameVisualizationReportFilter = "visualization_report_filter"

// VisualizationReportFilter 定时报告过自定义过滤组件信息
type VisualizationReportFilter struct {
	ID            int64  `gorm:"column:id;not null;comment:id" json:"id"`                    // id
	ReportID      int64  `gorm:"column:report_id;comment:定时报告id" json:"report_id"`           // 定时报告id
	TaskID        int64  `gorm:"column:task_id;comment:任务id" json:"task_id"`                 // 任务id
	ResourceID    int64  `gorm:"column:resource_id;comment:资源id" json:"resource_id"`         // 资源id
	DvType        string `gorm:"column:dv_type;comment:资源类型" json:"dv_type"`                 // 资源类型
	ComponentID   int64  `gorm:"column:component_id;comment:组件id" json:"component_id"`       // 组件id
	FilterID      int64  `gorm:"column:filter_id;comment:过滤项id" json:"filter_id"`            // 过滤项id
	FilterInfo    string `gorm:"column:filter_info;comment:过滤组件内容" json:"filter_info"`       // 过滤组件内容
	FilterVersion int32  `gorm:"column:filter_version;comment:过滤组件版本" json:"filter_version"` // 过滤组件版本
	CreateTime    int64  `gorm:"column:create_time;comment:创建时间" json:"create_time"`         // 创建时间
	CreateUser    string `gorm:"column:create_user;comment:创建人" json:"create_user"`          // 创建人
}

// TableName VisualizationReportFilter's table name
func (*VisualizationReportFilter) TableName() string {
	return TableNameVisualizationReportFilter
}
