// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package auto

const TableNameVisualizationTemplateCategoryMap = "visualization_template_category_map"

// VisualizationTemplateCategoryMap 模板表
type VisualizationTemplateCategoryMap struct {
	ID         string `gorm:"column:id;primaryKey;comment:主键" json:"id"`          // 主键
	CategoryID string `gorm:"column:category_id;comment:名称" json:"category_id"`   // 名称
	TemplateID string `gorm:"column:template_id;comment:父级id" json:"template_id"` // 父级id
}

// TableName VisualizationTemplateCategoryMap's table name
func (*VisualizationTemplateCategoryMap) TableName() string {
	return TableNameVisualizationTemplateCategoryMap
}
