// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package auto

const TableNameVisualizationBackground = "visualization_background"

// VisualizationBackground mapped from table <visualization_background>
type VisualizationBackground struct {
	ID             string `gorm:"column:id;primaryKey" json:"id"`
	Name           string `gorm:"column:name" json:"name"`
	Classification string `gorm:"column:classification;not null" json:"classification"`
	Content        string `gorm:"column:content" json:"content"`
	Remark         string `gorm:"column:remark" json:"remark"`
	Sort           int32  `gorm:"column:sort" json:"sort"`
	UploadTime     int64  `gorm:"column:upload_time" json:"upload_time"`
	BaseURL        string `gorm:"column:base_url" json:"base_url"`
	URL            string `gorm:"column:url" json:"url"`
}

// TableName VisualizationBackground's table name
func (*VisualizationBackground) TableName() string {
	return TableNameVisualizationBackground
}
