// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package auto

const TableNameXpackThresholdInstance = "xpack_threshold_instance"

// XpackThresholdInstance 告警实例表
type XpackThresholdInstance struct {
	ID       int64  `gorm:"column:id;primaryKey;comment:主键" json:"id"`               // 主键
	TaskID   int64  `gorm:"column:task_id;not null;comment:阈值信息ID" json:"task_id"`   // 阈值信息ID
	ExecTime int64  `gorm:"column:exec_time;not null;comment:检测时间" json:"exec_time"` // 检测时间
	Status   bool   `gorm:"column:status;not null;comment:数据状态" json:"status"`       // 数据状态
	Content  string `gorm:"column:content;comment:通知内容" json:"content"`              // 通知内容
	Msg      string `gorm:"column:msg;comment:报错信息" json:"msg"`                      // 报错信息
}

// TableName XpackThresholdInstance's table name
func (*XpackThresholdInstance) TableName() string {
	return TableNameXpackThresholdInstance
}
