// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package auto

const TableNameXpackSettingAuthentication = "xpack_setting_authentication"

// XpackSettingAuthentication 认证设置
type XpackSettingAuthentication struct {
	ID            int64  `gorm:"column:id;primaryKey;comment:主键" json:"id"`                 // 主键
	Name          string `gorm:"column:name;not null;comment:名称" json:"name"`               // 名称
	Type          string `gorm:"column:type;not null;comment:类型" json:"type"`               // 类型
	Enable        bool   `gorm:"column:enable;not null;comment:是否启用" json:"enable"`         // 是否启用
	SyncTime      int64  `gorm:"column:sync_time;not null;comment:同步时间" json:"sync_time"`   // 同步时间
	RelationalIds string `gorm:"column:relational_ids;comment:相关的ID" json:"relational_ids"` // 相关的ID
	PluginJSON    string `gorm:"column:plugin_json;comment:插件配置" json:"plugin_json"`        // 插件配置
	Synced        bool   `gorm:"column:synced;not null;comment:已同步" json:"synced"`          // 已同步
	Valid         bool   `gorm:"column:valid;not null;comment:有效" json:"valid"`             // 有效
}

// TableName XpackSettingAuthentication's table name
func (*XpackSettingAuthentication) TableName() string {
	return TableNameXpackSettingAuthentication
}
