// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package auto

const TableNameXpackThresholdInfo = "xpack_threshold_info"

// XpackThresholdInfo 告警信息表
type XpackThresholdInfo struct {
	ID                  int64  `gorm:"column:id;primaryKey;comment:主键" json:"id"`                               // 主键
	Name                string `gorm:"column:name;not null;comment:告警名称" json:"name"`                           // 告警名称
	Enable              bool   `gorm:"column:enable;not null;comment:是否启用" json:"enable"`                       // 是否启用
	RateType            int32  `gorm:"column:rate_type;not null;comment:频率类型" json:"rate_type"`                 // 频率类型
	RateValue           string `gorm:"column:rate_value;not null;comment:频率值" json:"rate_value"`                // 频率值
	ResourceType        string `gorm:"column:resource_type;not null;comment:资源类型" json:"resource_type"`         // 资源类型
	ResourceID          int64  `gorm:"column:resource_id;not null;comment:资源ID" json:"resource_id"`             // 资源ID
	ChartType           string `gorm:"column:chart_type;not null;comment:图表类型" json:"chart_type"`               // 图表类型
	ChartID             int64  `gorm:"column:chart_id;not null;comment:图表ID" json:"chart_id"`                   // 图表ID
	ThresholdRules      string `gorm:"column:threshold_rules;comment:告警规则" json:"threshold_rules"`              // 告警规则
	Recisetting         string `gorm:"column:recisetting;not null;default:0;comment:消息渠道" json:"recisetting"`   // 消息渠道
	ReciUsers           string `gorm:"column:reci_users;comment:接收人" json:"reci_users"`                         // 接收人
	ReciRoles           string `gorm:"column:reci_roles;comment:接收角色" json:"reci_roles"`                        // 接收角色
	ReciEmails          string `gorm:"column:reci_emails;comment:接收邮箱" json:"reci_emails"`                      // 接收邮箱
	ReciLarkGroups      string `gorm:"column:reci_lark_groups;comment:飞书群聊" json:"reci_lark_groups"`            // 飞书群聊
	ReciLarksuiteGroups string `gorm:"column:reci_larksuite_groups;comment:国际飞书群" json:"reci_larksuite_groups"` // 国际飞书群
	ReciWebhooks        string `gorm:"column:reci_webhooks;comment:Web hooks" json:"reci_webhooks"`             // Web hooks
	MsgTitle            string `gorm:"column:msg_title;not null;comment:消息标题" json:"msg_title"`                 // 消息标题
	MsgType             int32  `gorm:"column:msg_type;not null;comment:消息类型" json:"msg_type"`                   // 消息类型
	MsgContent          string `gorm:"column:msg_content;comment:消息内容" json:"msg_content"`                      // 消息内容
	RepeatSend          bool   `gorm:"column:repeat_send;not null;default:1;comment:是否重复发送" json:"repeat_send"` // 是否重复发送
	Status              bool   `gorm:"column:status;not null;comment:数据状态" json:"status"`                       // 数据状态
	Creator             int64  `gorm:"column:creator;not null;comment:创建者ID" json:"creator"`                    // 创建者ID
	CreatorName         string `gorm:"column:creator_name;not null;comment:创建人名称" json:"creator_name"`          // 创建人名称
	CreateTime          int64  `gorm:"column:create_time;not null;comment:创建时间" json:"create_time"`             // 创建时间
	Oid                 int64  `gorm:"column:oid;not null;comment:所属组织" json:"oid"`                             // 所属组织
}

// TableName XpackThresholdInfo's table name
func (*XpackThresholdInfo) TableName() string {
	return TableNameXpackThresholdInfo
}
