// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package auto

const TableNameXpackShare = "xpack_share"

// XpackShare 公共链接
type XpackShare struct {
	ID            int64  `gorm:"column:id;primaryKey;comment:ID" json:"id"`                             // ID
	Creator       int64  `gorm:"column:creator;not null;comment:创建人" json:"creator"`                    // 创建人
	Time          int64  `gorm:"column:time;not null;comment:创建时间" json:"time"`                         // 创建时间
	Exp           int64  `gorm:"column:exp;comment:过期时间" json:"exp"`                                    // 过期时间
	UUID          string `gorm:"column:uuid;not null;comment:uuid" json:"uuid"`                         // uuid
	Pwd           string `gorm:"column:pwd;comment:密码" json:"pwd"`                                      // 密码
	ResourceID    int64  `gorm:"column:resource_id;not null;comment:资源ID" json:"resource_id"`           // 资源ID
	Oid           int64  `gorm:"column:oid;not null;comment:组织ID" json:"oid"`                           // 组织ID
	Type          int32  `gorm:"column:type;not null;comment:业务类型" json:"type"`                         // 业务类型
	AutoPwd       bool   `gorm:"column:auto_pwd;not null;default:1;comment:自动生成密码" json:"auto_pwd"`     // 自动生成密码
	TicketRequire bool   `gorm:"column:ticket_require;not null;comment:ticket必须" json:"ticket_require"` // ticket必须
}

// TableName XpackShare's table name
func (*XpackShare) TableName() string {
	return TableNameXpackShare
}
