// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package auto

const TableNameXpackPlatformToken = "xpack_platform_token"

// XpackPlatformToken 认证token信息表
type XpackPlatformToken struct {
	ID         int32  `gorm:"column:id;primaryKey;comment:主键" json:"id"`                   // 主键
	Token      string `gorm:"column:token;not null;comment:认证token" json:"token"`          // 认证token
	CreateTime int64  `gorm:"column:create_time;not null;comment:创建时间" json:"create_time"` // 创建时间
	ExpTime    int64  `gorm:"column:exp_time;not null;comment:过期时间" json:"exp_time"`       // 过期时间
}

// TableName XpackPlatformToken's table name
func (*XpackPlatformToken) TableName() string {
	return TableNameXpackPlatformToken
}
