// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package auto

const TableNameXpackWebhook = "xpack_webhook"

// XpackWebhook mapped from table <xpack_webhook>
type XpackWebhook struct {
	ID          int64  `gorm:"column:id;primaryKey;comment:ID" json:"id"`                             // ID
	Name        string `gorm:"column:name;not null;comment:名称" json:"name"`                           // 名称
	URL         string `gorm:"column:url;not null;comment:url" json:"url"`                            // url
	ContentType string `gorm:"column:content_type;not null;comment:content_type" json:"content_type"` // content_type
	Secret      string `gorm:"column:secret;comment:密钥" json:"secret"`                                // 密钥
	Ssl         bool   `gorm:"column:ssl;not null;comment:开启ssl" json:"ssl"`                          // 开启ssl
	Oid         int64  `gorm:"column:oid;not null;comment:组织ID" json:"oid"`                           // 组织ID
	CreateTime  int64  `gorm:"column:create_time;not null;comment:创建时间" json:"create_time"`           // 创建时间
}

// TableName XpackWebhook's table name
func (*XpackWebhook) TableName() string {
	return TableNameXpackWebhook
}
