CREATE TABLE IF NOT EXISTS sys_governance_policy (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    org_id BIGINT UNSIGNED NOT NULL,
    policy_key VARCHAR(100) NOT NULL,
    policy_value VARCHAR(100) NOT NULL,
    updated_by VARCHAR(100) DEFAULT '',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_org_policy (org_id, policy_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
