// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        (unknown)
// source: proto/calcite/v1/calcite.proto

package calcitev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ParseSQLRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sql string `protobuf:"bytes,1,opt,name=sql,proto3" json:"sql,omitempty"`
}

func (x *ParseSQLRequest) Reset() {
	*x = ParseSQLRequest{}
	mi := &file_proto_calcite_v1_calcite_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseSQLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseSQLRequest) ProtoMessage() {}

func (x *ParseSQLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calcite_v1_calcite_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseSQLRequest.ProtoReflect.Descriptor instead.
func (*ParseSQLRequest) Descriptor() ([]byte, []int) {
	return file_proto_calcite_v1_calcite_proto_rawDescGZIP(), []int{0}
}

func (x *ParseSQLRequest) GetSql() string {
	if x != nil {
		return x.Sql
	}
	return ""
}

type ParseSQLResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NormalizedSql string `protobuf:"bytes,1,opt,name=normalized_sql,json=normalizedSql,proto3" json:"normalized_sql,omitempty"`
	RawSql        string `protobuf:"bytes,2,opt,name=raw_sql,json=rawSql,proto3" json:"raw_sql,omitempty"`
}

func (x *ParseSQLResponse) Reset() {
	*x = ParseSQLResponse{}
	mi := &file_proto_calcite_v1_calcite_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseSQLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseSQLResponse) ProtoMessage() {}

func (x *ParseSQLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calcite_v1_calcite_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseSQLResponse.ProtoReflect.Descriptor instead.
func (*ParseSQLResponse) Descriptor() ([]byte, []int) {
	return file_proto_calcite_v1_calcite_proto_rawDescGZIP(), []int{1}
}

func (x *ParseSQLResponse) GetNormalizedSql() string {
	if x != nil {
		return x.NormalizedSql
	}
	return ""
}

func (x *ParseSQLResponse) GetRawSql() string {
	if x != nil {
		return x.RawSql
	}
	return ""
}

type ValidateSQLRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sql string `protobuf:"bytes,1,opt,name=sql,proto3" json:"sql,omitempty"`
}

func (x *ValidateSQLRequest) Reset() {
	*x = ValidateSQLRequest{}
	mi := &file_proto_calcite_v1_calcite_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateSQLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateSQLRequest) ProtoMessage() {}

func (x *ValidateSQLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calcite_v1_calcite_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateSQLRequest.ProtoReflect.Descriptor instead.
func (*ValidateSQLRequest) Descriptor() ([]byte, []int) {
	return file_proto_calcite_v1_calcite_proto_rawDescGZIP(), []int{2}
}

func (x *ValidateSQLRequest) GetSql() string {
	if x != nil {
		return x.Sql
	}
	return ""
}

type ValidateSQLResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Valid         bool   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	NormalizedSql string `protobuf:"bytes,3,opt,name=normalized_sql,json=normalizedSql,proto3" json:"normalized_sql,omitempty"`
}

func (x *ValidateSQLResponse) Reset() {
	*x = ValidateSQLResponse{}
	mi := &file_proto_calcite_v1_calcite_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateSQLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateSQLResponse) ProtoMessage() {}

func (x *ValidateSQLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calcite_v1_calcite_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateSQLResponse.ProtoReflect.Descriptor instead.
func (*ValidateSQLResponse) Descriptor() ([]byte, []int) {
	return file_proto_calcite_v1_calcite_proto_rawDescGZIP(), []int{3}
}

func (x *ValidateSQLResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateSQLResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ValidateSQLResponse) GetNormalizedSql() string {
	if x != nil {
		return x.NormalizedSql
	}
	return ""
}

var File_proto_calcite_v1_calcite_proto protoreflect.FileDescriptor

var file_proto_calcite_v1_calcite_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x61, 0x6c, 0x63, 0x69, 0x74, 0x65, 0x2f,
	0x76, 0x31, 0x2f, 0x63, 0x61, 0x6c, 0x63, 0x69, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0a, 0x63, 0x61, 0x6c, 0x63, 0x69, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x22, 0x23, 0x0a, 0x0f,
	0x50, 0x61, 0x72, 0x73, 0x65, 0x53, 0x51, 0x4c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x10, 0x0a, 0x03, 0x73, 0x71, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x71,
	0x6c, 0x22, 0x52, 0x0a, 0x10, 0x50, 0x61, 0x72, 0x73, 0x65, 0x53, 0x51, 0x4c, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x6e, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x69,
	0x7a, 0x65, 0x64, 0x5f, 0x73, 0x71, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x6e,
	0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x53, 0x71, 0x6c, 0x12, 0x17, 0x0a, 0x07,
	0x72, 0x61, 0x77, 0x5f, 0x73, 0x71, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72,
	0x61, 0x77, 0x53, 0x71, 0x6c, 0x22, 0x26, 0x0a, 0x12, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74,
	0x65, 0x53, 0x51, 0x4c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x73,
	0x71, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x71, 0x6c, 0x22, 0x6c, 0x0a,
	0x13, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x53, 0x51, 0x4c, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x6e, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x69, 0x7a,
	0x65, 0x64, 0x5f, 0x73, 0x71, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x6e, 0x6f,
	0x72, 0x6d, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x53, 0x71, 0x6c, 0x32, 0xa7, 0x01, 0x0a, 0x0e,
	0x43, 0x61, 0x6c, 0x63, 0x69, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x45,
	0x0a, 0x08, 0x50, 0x61, 0x72, 0x73, 0x65, 0x53, 0x51, 0x4c, 0x12, 0x1b, 0x2e, 0x63, 0x61, 0x6c,
	0x63, 0x69, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x61, 0x72, 0x73, 0x65, 0x53, 0x51, 0x4c,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x69, 0x74,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x61, 0x72, 0x73, 0x65, 0x53, 0x51, 0x4c, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4e, 0x0a, 0x0b, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74,
	0x65, 0x53, 0x51, 0x4c, 0x12, 0x1e, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x69, 0x74, 0x65, 0x2e, 0x76,
	0x31, 0x2e, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x53, 0x51, 0x4c, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x69, 0x74, 0x65, 0x2e, 0x76,
	0x31, 0x2e, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x53, 0x51, 0x4c, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x2d, 0x5a, 0x2b, 0x64, 0x61, 0x74, 0x61, 0x65, 0x61, 0x73,
	0x65, 0x2f, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x63, 0x61, 0x6c, 0x63, 0x69, 0x74, 0x65, 0x2f, 0x76, 0x31, 0x3b, 0x63, 0x61, 0x6c, 0x63, 0x69,
	0x74, 0x65, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_calcite_v1_calcite_proto_rawDescOnce sync.Once
	file_proto_calcite_v1_calcite_proto_rawDescData = file_proto_calcite_v1_calcite_proto_rawDesc
)

func file_proto_calcite_v1_calcite_proto_rawDescGZIP() []byte {
	file_proto_calcite_v1_calcite_proto_rawDescOnce.Do(func() {
		file_proto_calcite_v1_calcite_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_calcite_v1_calcite_proto_rawDescData)
	})
	return file_proto_calcite_v1_calcite_proto_rawDescData
}

var file_proto_calcite_v1_calcite_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_calcite_v1_calcite_proto_goTypes = []any{
	(*ParseSQLRequest)(nil),     // 0: calcite.v1.ParseSQLRequest
	(*ParseSQLResponse)(nil),    // 1: calcite.v1.ParseSQLResponse
	(*ValidateSQLRequest)(nil),  // 2: calcite.v1.ValidateSQLRequest
	(*ValidateSQLResponse)(nil), // 3: calcite.v1.ValidateSQLResponse
}
var file_proto_calcite_v1_calcite_proto_depIdxs = []int32{
	0, // 0: calcite.v1.CalciteService.ParseSQL:input_type -> calcite.v1.ParseSQLRequest
	2, // 1: calcite.v1.CalciteService.ValidateSQL:input_type -> calcite.v1.ValidateSQLRequest
	1, // 2: calcite.v1.CalciteService.ParseSQL:output_type -> calcite.v1.ParseSQLResponse
	3, // 3: calcite.v1.CalciteService.ValidateSQL:output_type -> calcite.v1.ValidateSQLResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_calcite_v1_calcite_proto_init() }
func file_proto_calcite_v1_calcite_proto_init() {
	if File_proto_calcite_v1_calcite_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_calcite_v1_calcite_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_calcite_v1_calcite_proto_goTypes,
		DependencyIndexes: file_proto_calcite_v1_calcite_proto_depIdxs,
		MessageInfos:      file_proto_calcite_v1_calcite_proto_msgTypes,
	}.Build()
	File_proto_calcite_v1_calcite_proto = out.File
	file_proto_calcite_v1_calcite_proto_rawDesc = nil
	file_proto_calcite_v1_calcite_proto_goTypes = nil
	file_proto_calcite_v1_calcite_proto_depIdxs = nil
}
