// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: proto/calcite/v1/calcite.proto

package calcitev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CalciteService_ParseSQL_FullMethodName    = "/calcite.v1.CalciteService/ParseSQL"
	CalciteService_ValidateSQL_FullMethodName = "/calcite.v1.CalciteService/ValidateSQL"
)

// CalciteServiceClient is the client API for CalciteService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CalciteServiceClient interface {
	ParseSQL(ctx context.Context, in *ParseSQLRequest, opts ...grpc.CallOption) (*ParseSQLResponse, error)
	ValidateSQL(ctx context.Context, in *ValidateSQLRequest, opts ...grpc.CallOption) (*ValidateSQLResponse, error)
}

type calciteServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCalciteServiceClient(cc grpc.ClientConnInterface) CalciteServiceClient {
	return &calciteServiceClient{cc}
}

func (c *calciteServiceClient) ParseSQL(ctx context.Context, in *ParseSQLRequest, opts ...grpc.CallOption) (*ParseSQLResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ParseSQLResponse)
	err := c.cc.Invoke(ctx, CalciteService_ParseSQL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calciteServiceClient) ValidateSQL(ctx context.Context, in *ValidateSQLRequest, opts ...grpc.CallOption) (*ValidateSQLResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateSQLResponse)
	err := c.cc.Invoke(ctx, CalciteService_ValidateSQL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CalciteServiceServer is the server API for CalciteService service.
// All implementations must embed UnimplementedCalciteServiceServer
// for forward compatibility.
type CalciteServiceServer interface {
	ParseSQL(context.Context, *ParseSQLRequest) (*ParseSQLResponse, error)
	ValidateSQL(context.Context, *ValidateSQLRequest) (*ValidateSQLResponse, error)
	mustEmbedUnimplementedCalciteServiceServer()
}

// UnimplementedCalciteServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCalciteServiceServer struct{}

func (UnimplementedCalciteServiceServer) ParseSQL(context.Context, *ParseSQLRequest) (*ParseSQLResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ParseSQL not implemented")
}
func (UnimplementedCalciteServiceServer) ValidateSQL(context.Context, *ValidateSQLRequest) (*ValidateSQLResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateSQL not implemented")
}
func (UnimplementedCalciteServiceServer) mustEmbedUnimplementedCalciteServiceServer() {}
func (UnimplementedCalciteServiceServer) testEmbeddedByValue()                        {}

// UnsafeCalciteServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CalciteServiceServer will
// result in compilation errors.
type UnsafeCalciteServiceServer interface {
	mustEmbedUnimplementedCalciteServiceServer()
}

func RegisterCalciteServiceServer(s grpc.ServiceRegistrar, srv CalciteServiceServer) {
	// If the following call pancis, it indicates UnimplementedCalciteServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CalciteService_ServiceDesc, srv)
}

func _CalciteService_ParseSQL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParseSQLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalciteServiceServer).ParseSQL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CalciteService_ParseSQL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalciteServiceServer).ParseSQL(ctx, req.(*ParseSQLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CalciteService_ValidateSQL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateSQLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalciteServiceServer).ValidateSQL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CalciteService_ValidateSQL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalciteServiceServer).ValidateSQL(ctx, req.(*ValidateSQLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CalciteService_ServiceDesc is the grpc.ServiceDesc for CalciteService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CalciteService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "calcite.v1.CalciteService",
	HandlerType: (*CalciteServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ParseSQL",
			Handler:    _CalciteService_ParseSQL_Handler,
		},
		{
			MethodName: "ValidateSQL",
			Handler:    _CalciteService_ValidateSQL_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/calcite/v1/calcite.proto",
}
